server:
  port: 7399
  tomcat:
    max-http-form-post-size: -1
#关闭模板引擎的我缓存
spring:
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
  messages:
    basename: i18n.login
  profiles:
    active: dev

mybatis-plus:
  type-aliases-package: com.du.blog.entity
  mapper-locations: classpath:mapper/*.xml

shiro-redis:
  enabled: true
  shiro-manager:
    host: 127.0.0.1:6379
du:
  jwt:
    secret: afwragviuxjqcedveioskd
    expire:
    header: Authorization




